#!/bin/dash

case "$XDG_SESSION_TYPE" in
wayland)
  WOBSOCK=$XDG_RUNTIME_DIR/wob.sock
  ;;
x11)
  WOBSOCK=/tmp/xobpipe
  ;;
esac

brightnessctl set $1 | sed -En 's/.*\(([0-9]+)%\).*/\1/p' >$WOBSOCK
kill -35 "$(cat ~/.cache/blocks)"
