#!/bin/bash

case $1 in
up)
  brightnessctl set +5% | sed -En 's/.*\(([0-9]+)%\).*/\1/p' >$WOBSOCK
  ;;
down)
  brightnessctl set 5%- | sed -En 's/.*\(([0-9]+)%\).*/\1/p' >$WOBSOCK
  ;;
slowup)
  brightnessctl set +1% | sed -En 's/.*\(([0-9]+)%\).*/\1/p' >$WOBSOCK
  ;;
slowdown)
  brightnessctl set 1%- | sed -En 's/.*\(([0-9]+)%\).*/\1/p' >$WOBSOCK
  ;;
esac
