#!/bin/dash

case "$1" in
*dark*)
  COLOR=dark
  echo $COLOR >~/.config/scripts/colors/status/current_color
  gsettings set org.gnome.desktop.interface color-scheme \'prefer-dark\'
  ;;
*)
  COLOR=light
  echo $COLOR >~/.config/scripts/colors/status/current_color
  gsettings set org.gnome.desktop.interface color-scheme \'prefer-light\'
  ;;
esac

MODE=$(head -n 1 ~/.config/scripts/colors/status/status)
THEME=$(tail -n 1 ~/.config/scripts/colors/status/status)
TYPE=$(cat ~/.config/scripts/colors/status/type)

case "$MODE" in
custom)
  ~/.config/scripts/colors/color-scheme --$THEME
  ;;
matugen)
  matugen -t $TYPE -m $COLOR image $1
  ;;
*) ;;
esac

cp $1 ~/.swaylock/wallpaper
