#!/bin/bash

COLOR_SCHEME=$(gsettings get org.gnome.desktop.interface color-scheme)

if [[ $COLOR_SCHEME == "'prefer-dark'" ]]; then
  matugen -m dark image $1
fi

if [[ $COLOR_SCHEME == "'prefer-light'" ]]; then
  matugen -m light image $1
fi

cp $1 ~/.swaylock/wallpaper
