#!/bin/bash

case $1 in
mute)
  wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && (wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q MUTED && echo 0 >$WOBSOCK) || wpctl get-volume @DEFAULT_AUDIO_SINK@ | sed 's/[^0-9]//g' >$WOBSOCK
  ;;
up)
  (wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q MUTED && echo 0 >$WOBSOCK) || (wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ && wpctl get-volume @DEFAULT_AUDIO_SINK@ | sed 's/[^0-9]//g' >$WOBSOCK)
  ;;
down)
  (wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q MUTED && echo 0 >$WOBSOCK) || (wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && wpctl get-volume @DEFAULT_AUDIO_SINK@ | sed 's/[^0-9]//g' >$WOBSOCK)
  ;;
slowup)
  (wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q MUTED && echo 0 >$WOBSOCK) || (wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%+ && wpctl get-volume @DEFAULT_AUDIO_SINK@ | sed 's/[^0-9]//g' >$WOBSOCK)
  ;;
slowdown)
  (wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q MUTED && echo 0 >$WOBSOCK) || (wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%- && wpctl get-volume @DEFAULT_AUDIO_SINK@ | sed 's/[^0-9]//g' >$WOBSOCK)
  ;;
esac
