#!/bin/bash

case "$XDG_SESSION_TYPE" in
wayland)
  WOBSOCK=$XDG_RUNTIME_DIR/wob.sock
  ;;
x11)
  WOBSOCK=/tmp/xobpipe
  ;;
esac

case "$1" in
sink)
  target="@DEFAULT_AUDIO_SINK@"
  target_pip=-34
  ;;
source)
  target="@DEFAULT_AUDIO_SOURCE@"
  target_pip=-36
  ;;
esac

get_current_volume() {
  wpctl get-volume "$target" | sed 's/[^0-9]//g'
}

toggle_mute() {
  wpctl set-mute "$target" toggle
  if wpctl get-volume "$target" | grep -q MUTED; then
    output_volume 0
  else
    output_volume "$(get_current_volume)"
  fi
}

set_volume() {
  local volume_level=$1
  if ! wpctl get-volume "$target" | grep -q MUTED; then
    wpctl set-volume "$target" "$volume_level"
    output_volume "$(get_current_volume)"
  else
    output_volume 0
  fi
}

output_volume() {
  local volume_val=$1
  echo "$volume_val" >"$WOBSOCK"
  if [[ -f ~/.cache/blocks ]]; then
    kill "$target_pip" "$(cat ~/.cache/blocks)"
  fi
}

case "$2" in
mute)
  toggle_mute
  ;;
*)
  set_volume "$2"
  ;;
esac
