shadowscolor = 0x000000ff
rootcolor = 0x899391ff
bordercolor = 0x0e151400
focuscolor = 0x81d5cbff
maximizescreencolor = 0xb1ccc7ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xaec9e6ff
globalcolor = 0x00504aff
overlaycolor = 0x324b48ff
