# autostart
exec-once=awww-daemon
exec-once=mako
exec-once=ydotoold
exec-once=wl-paste --type text --watch cliphist store
exec-once=wl-paste --type image --watch cliphist store
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once=/usr/lib/xdg-desktop-portal-wlr

# restart
exec=~/.config/scripts/waybar-restart
exec=~/.config/scripts/wobd
exec=fcitx5 -d --replace
