shell_integration enabled
shell fish

font_size 12
background_opacity 0.6

window_padding_width 0 5 0

remember_window_size no
initial_window_width 1024
initial_window_height 768

# BEGIN_KITTY_THEME
# Rosé Pine
include current-theme.conf
# END_KITTY_THEME


# BEGIN_KITTY_FONTS
font_family      family='Maple Mono NL NF CN' postscript_name=MapleMonoNL-NF-CN-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
