source=~/.config/mango/config/base.conf
source=~/.config/mango/config/bind.conf
source=~/.config/mango/config/color.conf
source=~/.config/mango/config/env.conf
source=~/.config/mango/config/rule.conf
source=~/.config/mango/config/start.conf
