#!/bin/sh

PREFIX='󰖨'

get_backlight() {
  now_bright=$(cat /sys/class/backlight/intel_backlight/actual_brightness)
  max_bright=$(cat /sys/class/backlight/intel_backlight/max_brightness)
  backlight="$(expr $now_bright \* 100 / $max_bright)%"
  echo $PREFIX$backlight
}

get_backlight
