#!/bin/sh

speaker=""
speaker_muted=""
earphone="󱡏"
earphone_muted="󱡐"
microphone=""
microphone_muted=""

case "$1" in
sink)
  target="@DEFAULT_AUDIO_SINK@"
  ;;
source)
  target="@DEFAULT_AUDIO_SOURCE@"
  ;;
esac

get_volume() {
  wpctl get-volume "$target"
}

volume=$(get_volume | sed 's/[^0-9]//g; s/^0//')

if get_volume | grep -q MUTED; then
  is_muted=true
else
  is_muted=false
fi

if wpctl status | grep -q bluez_input; then
  has_bluetooth=true
else
  has_bluetooth=false
fi

case "$1" in
sink)
  if $is_muted; then
    $has_bluetooth && echo "$earphone_muted$volume%" || echo "$speaker_muted$volume%"
  else
    $has_bluetooth && echo "$earphone$volume%" || echo "$speaker$volume%"
  fi
  ;;
source)
  $is_muted && echo "$microphone_muted$volume%" || echo "$microphone$volume%"
  ;;
esac
