shadowscolor = 0xecf5edff
rootcolor = 0x9da9a0ff
bordercolor = 0x232a2eff
focuscolor = 0x434f55ff
maximizescreencolor = 0x232a2eff
urgentcolor = 0xe66868ff
scratchpadcolor = 0x333c43ff
globalcolor = 0x8aaec0ff
overlaycolor = 0x5c8ca7ff
