shadowscolor = 0xfaf4edff
rootcolor = 0xfffaf3ff
bordercolor = 0x9e8e8bff
focuscolor = 0xd7827eff
maximizescreencolor = 0x56949fff
urgentcolor = 0xb4637aff
scratchpadcolor = 0x286983ff
globalcolor = 0xe5cdccff
overlaycolor = 0xc7dde1ff
