shadowscolor = 0x000000ff
rootcolor = 0x000000ff
bordercolor = 0x724f61ff
focuscolor = 0xff8cb3ff
maximizescreencolor = 0xffb3ccff
urgentcolor = 0xff99b8ff
scratchpadcolor = 0xffcce0ff
globalcolor = 0xd90049ff
overlaycolor = 0xff0054ff
