shadowscolor = 0xf0d0e0ff
rootcolor = 0xfff5faff
bordercolor = 0xb38099ff
focuscolor = 0xe57399ff
maximizescreencolor = 0xff99b8ff
urgentcolor = 0xff99b8ff
scratchpadcolor = 0xffb3ccff
globalcolor = 0xebc6d3ff
overlaycolor = 0xf7bacdff
