# Appearance
gappih=4
gappiv=4
gappoh=8
gappov=8
scratchpad_width_ratio=0.8
scratchpad_height_ratio=0.9
borderpx=2
rootcolor=0x201b14ff
bordercolor=0x{{ colors.on_primary.default.hex_stripped }}00
focuscolor=0x{{ colors.primary.default.hex_stripped }}ff
maximizescreencolor=0x{{ colors.tertiary.default.hex_stripped }}ff
urgentcolor=0xff0000ff
scratchpadcolor=0x{{ colors.on_primary_container.default.hex_stripped }}ff
globalcolor=0x{{ colors.error.default.hex_stripped }}ff
overlaycolor=0x{{ colors.secondary_fixed.default.hex_stripped }}ff
