#!/bin/bash

if pgrep "wlrsetroot" >/dev/null; then
  pkill "wlrsetroot"
fi

wlrsetroot -bitmap Pictures/bitmap-walls/patterns/dots_diag.xbm -bg "{{colors.surface.default.hex}}" -fg "{{colors.primary.default.hex}}" &

disown
